[env:T-Dongle-S3]
platform = espressif32
framework = arduino
board = dongles3
build_flags =
	-I..
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-D TFT_ESPI_USER_SETUP_PATH=\"../../configs/tft_setup.h\"
monitor_speed = 115200
lib_deps = fastled/FastLED@^3.10.3
